# Generated by Django 5.1.3 on 2025-02-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('読売ジャイアンツ', '読売ジャイアンツ'), ('阪神タイガース', '阪神タイガース'), ('中日ドラゴンズ', '中日ドラゴンズ'), ('横浜DeNAベイスターズ', '横浜DeNAベイスターズ'), ('広島東洋カープ', '広島東洋カープ'), ('東京ヤクルトスワローズ', '東京ヤクルトスワローズ'), ('オリックス・バファローズ', 'オリックス・バファローズ'), ('福岡ソフトバンクホークス', '福岡ソフトバンクホークス'), ('北海道日本ハムファイターズ', '北海道日本ハムファイターズ'), ('千葉ロッテマリーンズ', '千葉ロッテマリーンズ'), ('埼玉西武ライオンズ', '埼玉西武ライオンズ'), ('東北楽天ゴールデンイーグルス', '東北楽天ゴールデンイーグルス'), ('大阪近鉄バファローズ', '大阪近鉄バファローズ'), ('その他', 'その他')], max_length=100),
        ),
    ]
