# Generated by Django 5.1.3 on 2025-02-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
