# Generated by Django 5.1.3 on 2025-02-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0005_alter_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='award',
            field=models.TextField(default='受賞歴なし'),
        ),
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='p_and_h',
            field=models.CharField(choices=[('右投右打', '右投右打'), ('右投左打', '右投左打'), ('左投左打', '左投左打'), ('左投右打', '左投右打'), ('右投両打', '右投両打'), ('左投両打', '左投両打')], default='その他', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='place',
            field=models.CharField(default='不明', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('投手', '投手'), ('捕手', '捕手'), ('一塁手', '一塁手'), ('二塁手', '二塁手'), ('三塁手', '三塁手'), ('遊撃手', '遊撃手'), ('外野手', '外野手'), ('指名打者', '指名打者')], default='その他', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.CharField(default='不明', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.TextField(default='受賞タイトルなし'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_record',
            field=models.TextField(default='記録なし'),
        ),
    ]
