# Generated by Django 5.1.3 on 2025-02-22 03:23

import helloApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0006_player_award_player_date_player_link_player_p_and_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=helloApp.models.player_image_path),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.TextField(default='プロフィールなし'),
        ),
    ]
