# Generated by Django 5.1.3 on 2025-02-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0008_player_team_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='long_profile',
            field=models.TextField(default='プロフィールなし'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.TextField(),
        ),
    ]
