# Generated by Django 5.1.3 on 2025-03-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0009_player_long_profile_alter_player_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
